version: '2'

services:

  cryptopus-mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=cryptopus
      - MYSQL_PASSWORD=cryptopus
      - MYSQL_DATABASE=cryptopus_development
      - MYSQL_ROOT_PASSWORD=cryptopus
